### ISSUE TITLE
Crear Script SQL de Creación del Schema de la Base

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#1]
Tienen que crear un script con la creación del schema de la base de datos. Porque? Porque si quiero correr sus test, necesito tener las tablas creadas y al no tener el script tengo que ver que tablas usan en su proyecto y con que columnas, etc. Entonces no esta bueno eso.

Creen el script y lo adjuntan en el proyecto. Un buen lugar para el archivo es dentro del directorio "src/main/resources", que es el lugar por convención de maven para adjuntar recursos externos al código. También dentro de el pueden categorizar los archivos, por ejemplo "src/main/resources/db/createSchema.sql"

**Comment by LaimeJesus** [comment]
Una duda con respecto al script. Puedo exportar el archivo que me crea workbench? o deberia crear el archivo sql a mano. Ya que en el export no me aparece el id como autoincrement y tira unos errores cuando lo cambio.

**Comment by nnydjesus** [comment]
Con el export del workbench es mas que suficiente. 
Estas seguro que tenes el autoincrement activado? Porque en el código estaban seteando a mano el id.
Fijate en el workbench si la columna tiene el autoincrement (podes verlo con la opción de Table Inspector o con el alter Table)

![screen shot 2016-03-30 at 11 26 47 am](https://cloud.githubusercontent.com/assets/1201972/14145767/6ecee534-f66b-11e5-899d-25ff74f3a36a.png)

![screen shot 2016-03-30 at 11 27 10 am](https://cloud.githubusercontent.com/assets/1201972/14145769/725dc094-f66b-11e5-9b7c-179322b41b50.png)

Fixate que se tiene que ver algo asi:

Inspector - Solapa columns:

![screen shot 2016-03-30 at 11 35 51 am](https://cloud.githubusercontent.com/assets/1201972/14145987/65ceb224-f66c-11e5-8561-916d7f7db8e1.png)

Alter Table:

![screen shot 2016-03-30 at 11 36 06 am](https://cloud.githubusercontent.com/assets/1201972/14145947/393af150-f66c-11e5-8178-316b0defeb40.png)
