### ISSUE TITLE
El BuscadorDeVuelos debería ser un servicio

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#11]
El BuscadorDeVuelos tiene toda la pinta de un servicio.

**Comment by gguzman89** [comment]
buenas... no entiendo en la manera mencionas que puede ser un servicio, lo decis por el echo de que tiene un repo de aerolineas? porque tiene que estar mejor organizado en otro package? porque presta un servicio de busqueda?

saludos

**Comment by gguzman89** [comment]
buenas... no entiendo en la manera mencionas que puede ser un servicio, lo decis por el echo de que tiene un repo de aerolineas? porque tiene que estar mejor organizado en otro package? porque presta un servicio de busqueda?

saludos

**Comment by nnydjesus** [comment]
Hola, 

Primero pensa que lo tienen categorizado como un objeto de dominio. Si ese buscadorDeVuelos crea una session de Hibernate y habla con la persistencia, para vos, tiene sentido que un objeto del modelo conozca de La sesiones y la persistencia??

Otra cosa, uno de los requerimientos del TP es poder buscar con diferentes criterios. Y como hablamos en clase, esos requerimientos deberían estar modelado como servicios (que dentro del servicio se puede usar toda la lógica del modelo + la persistencia), como lo venían haciendo con el TP1 y parte del TP2.

Y otra cosa muy importante, es que ustedes no tienen que cerrar el issue, los issues lo cerramos nosotros cuando verificamos que esta corregido.
