### ISSUE TITLE
Mucha responsabilidad en el reservar del ServicioDeReserva

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#12]
Tienen este código: 

![screen shot 2016-04-25 at 1 04 43 pm](https://cloud.githubusercontent.com/assets/1201972/14790141/6017460a-0ae6-11e6-8597-f88ac7a4da0f.png)

Las validaciones están bien, pero no lo que no esta bien es la forma en la que se realizan.
Si tenes que validar que un vuelo pertenezca a una aerolínea, no podría ser una responsabilidad de la aerolínea? 

Lo mismo va para los vuelos-tramos, tramos-asientos.

Podrias tener una validación en cascada.. por ejemplo:

![screen shot 2016-04-25 at 1 10 01 pm](https://cloud.githubusercontent.com/assets/1201972/14790302/0c23f556-0ae7-11e6-8eb4-3f8ce4754dc9.png)

(Aunque no compila, pero podría ser una buena forma de delegar las validaciones a los objeto de dominio )

**Comment by gguzman89** [comment]
hola... en todos los casos validarReserva que estaria validando? que exista esa reserva?
por ej: en aerolinea.validarReserva(vuelo, tramo, asiento) estarias validando que ese vuelo exista o pertenezca a esa aerolinea

**Comment by nnydjesus** [comment]
Hola, 

No, cada objeto sabe que cosas tiene que validar para poder realizar una reserva. Fijate que estas validado hacer una reserva, no validar una reserva existente.
