### ISSUE TITLE
Se podría resolver un una query que te devuelva true o false

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#17]
En la consulta de **viajeA**  te traes todos los vuelos en los que reservaste algún asiento y recorres los tramos a mano, eso se podría resolver con una sola query... y que te devuelva un true o false o que te devuelva el tramo y si esta... es que viajó a ese lugar y si no... no!

![screen shot 2016-06-05 at 1 19 25 pm](https://cloud.githubusercontent.com/assets/1201972/15806721/9de0a9cc-2b20-11e6-9a72-af4d99dea0fd.png)

**Comment by LaimeJesus** [comment]
No me habia dado cuenta pero eso se podia hacer mas sencillo. Simplemente combinando 2 condiciones: la condicion de asiento reservado y la condicion de destino, es decir la que filtra por el destino de un tramo y la otra que filtra los asientos reservados de un tramo. Luego lo que preguntaria es si hay vuelos que cumplan con esa caracteristica, resultadoDeBusqueda > 0. 
Igual no me quedo muy claro lo de hacer otra query que devuelva un booleano. Mi servicio de busqueda solo trae vuelos por eso tenia q recorrer los vuelos.
