### ISSUE TITLE
Armar la lista de filters para la agregación se puede simplificar

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#19]
Ahora tenes eso:

![screen shot 2016-06-05 at 1 43 38 pm](https://cloud.githubusercontent.com/assets/1201972/15806864/d3ea4bec-2b23-11e6-8667-e83638cc39ac.png)

Fijate que esta muy atado a la cantidad de visibilidades que tenes... sumado a la cantidad de código repetido...

se podría simplificar asi:

![screen shot 2016-06-05 at 1 43 26 pm](https://cloud.githubusercontent.com/assets/1201972/15806872/02d18862-2b24-11e6-944e-44d57d53ad85.png)

**Comment by LaimeJesus** [comment]
Me rompio la cabeza como esa solucion es igual a la que tengo pero que ademas si es escalable.
