### ISSUE TITLE
Manejar Excepciones en los Tests

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#2]
Tienen tests donde esperan una excepción y en varios casos manejan las excepciones sin hacer nada "importante". por ejemplo:

![screen shot 2016-03-29 at 10 49 40 pm](https://cloud.githubusercontent.com/assets/1201972/14129445/8f6935a8-f600-11e5-858f-cfbb2db54cac.png)

JUnit tiene una forma de hacer un assert esperando una excepción sin manejarla.

![screen shot 2016-03-29 at 10 51 53 pm](https://cloud.githubusercontent.com/assets/1201972/14129507/0aef7c78-f601-11e5-96e2-8f17393030f7.png)

**Comment by LaimeJesus** [comment]
Olvide preguntarte sobre este problema, a que te referis con no hacer nada importante. Deberia testear algo sobre la exception? o handlearla con algo? no lo tengo muy claro.

**Comment by nnydjesus** [comment]
Lo de "nada importante" me refería al `assertFalse(sudo.repositorio.contiene("nickname", nickname))`
ya que estas esperando una Excepción **UsuarioNoEstaEnElServicioException**. En este caso parece redundante con el assert y ese assert no te aporta mucho en el test.

Hay casos donde si es importante hacer asserts si ocurre una excepción, por ejemplo:
Si estoy probando una transferencia de una cuenta a otra. Y en el método transferir débito de una cuenta y después acredito en la otra. Imaginate que la acreditación puede tirar una excepción. Entonces si llega a tirar esa excepción, tengo que asegurarme que el primer débito no se haya efectuado, porque sino los datos quedan inconsistentes.  

Se entendió?

**Comment by nnydjesus** [comment]
Lo de "nada importante" me refería al `assertFalse(sudo.repositorio.contiene("nickname", nickname))`
ya que estas esperando una Excepción **UsuarioNoEstaEnElServicioException**. En este caso parece redundante con el assert y ese assert no te aporta mucho en el test.

Hay casos donde si es importante hacer asserts si ocurre una excepción, por ejemplo:
Si estoy probando una transferencia de una cuenta a otra. Y en el método transferir débito de una cuenta y después acredito en la otra. Imaginate que la acreditación puede tirar una excepción. Entonces si llega a tirar esa excepción, tengo que asegurarme que el primer débito no se haya efectuado, porque sino los datos quedan inconsistentes.  


Se entendió?

**Comment by LaimeJesus** [comment]
Osea deberia asegurarme de testear una excepcion cuando necesito manejarla de alguna manera. No como ahora que solo necesitamos levantarla. O eso entendi

**Comment by nnydjesus** [comment]
Osea... manejas la excepción cuando necesitas asegurar cosas después de la excepción. Sino con hacer la declaración de que en ese test se espera tal excepción (como se muestra en la segunda imagen que adjunte) alcanza
