### ISSUE TITLE
Delegar al usuario la responsabilidad de saber si esta validado

### ISSUE THREAD

**Issue by nnydjesus** [LaimeJesus/aterrizar.com#4]
Estaria bueno que el usuario tenga esa responsabilidad.

![screen shot 2016-03-29 at 11 09 00 pm](https://cloud.githubusercontent.com/assets/1201972/14129789/9157ea00-f603-11e5-8cf1-c039c15ce4ab.png)

**Comment by nnydjesus** [comment]
Uh, después vi que el usuario tiene el mensaje:

![screen shot 2016-03-29 at 11 13 52 pm](https://cloud.githubusercontent.com/assets/1201972/14129819/f64d3118-f603-11e5-8a69-7a13d318c5a0.png)

**Comment by LaimeJesus** [comment]
si, tiene el mensaje pero no lo estamos usando en ese lugar. Asi que creo que igual esta mal. Se corregira
